# typed: false
# frozen_string_literal: true

# Generated by cmd/formulagen in frodi-karlsson/onesie. Do not edit it by hand.
class Onesie < Formula
  desc "Command line interface for TypeSafe Jev"
  homepage "https://github.com/frodi-karlsson/onesie"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.3.0/onesie_0.3.0_darwin_arm64.tar.gz"
      sha256 "a66550e3533220810b77d74961eb50671bd7231b8067ab8692b50dd74cf48ef6"
    end
    on_intel do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.3.0/onesie_0.3.0_darwin_amd64.tar.gz"
      sha256 "561fcd60ca188f6de12a29984193e6d1ca1c5176525de8bbd09403a1c8e2170f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.3.0/onesie_0.3.0_linux_arm64.tar.gz"
      sha256 "c6d68c78fc13ce59e95df72c16582583537903b997f93ce6360e7a8e101bb9a2"
    end
    on_intel do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.3.0/onesie_0.3.0_linux_amd64.tar.gz"
      sha256 "a07326e62e31fbcd123453a4fece00e6ef1ecb075f314745b988f87683351cc3"
    end
  end

  def install
    bin.install "onesie"
    bash_completion.install "completions/onesie.bash" => "onesie"
    zsh_completion.install "completions/onesie.zsh" => "_onesie"
    fish_completion.install "completions/onesie.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/onesie version")
  end
end
