# typed: false
# frozen_string_literal: true

# Generated by cmd/formulagen in frodi-karlsson/onesie. Do not edit it by hand.
class Onesie < Formula
  desc "Ask System One models typed questions about text from the shell"
  homepage "https://github.com/frodi-karlsson/onesie"
  version "0.4.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.4.2/onesie_0.4.2_darwin_arm64.tar.gz"
      sha256 "024779ce119744503f9f4450f4dec23e9eb57b66ae2195932e4ddbd4a97169bc"
    end
    on_intel do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.4.2/onesie_0.4.2_darwin_amd64.tar.gz"
      sha256 "60713841873e1a904fce5aa1f0ff02705763859a5ff548b3d602c4835b9314fc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.4.2/onesie_0.4.2_linux_arm64.tar.gz"
      sha256 "780999eb7d9b2993c40f3d0824a07436f067b83569c8983a5d09162f415c3d08"
    end
    on_intel do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.4.2/onesie_0.4.2_linux_amd64.tar.gz"
      sha256 "0aefaf86520d149ebabcf156f2d288f5c6c3b257f73bc7a1481a31af77d465c4"
    end
  end

  def install
    bin.install "onesie"
    bash_completion.install "completions/onesie.bash" => "onesie"
    zsh_completion.install "completions/onesie.zsh" => "_onesie"
    fish_completion.install "completions/onesie.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/onesie version")
  end
end
