# typed: false
# frozen_string_literal: true

# Generated by cmd/formulagen in frodi-karlsson/onesie. Do not edit it by hand.
class Onesie < Formula
  desc "Command line interface for TypeSafe Jev"
  homepage "https://github.com/frodi-karlsson/onesie"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.2.0/onesie_0.2.0_darwin_arm64.tar.gz"
      sha256 "122a3c3dd07c91efdf999ca6f40946190707bbcdffbf77dcb312d1c2661c9468"
    end
    on_intel do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.2.0/onesie_0.2.0_darwin_amd64.tar.gz"
      sha256 "7a8fa2f44572215fb743bc83a6aac56400efdb8204e8e8699004f22d9c6cbd79"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.2.0/onesie_0.2.0_linux_arm64.tar.gz"
      sha256 "6055f190c4829b1b15a8ec2b0b81a963658f6eb481e3bc2e86610810131798c7"
    end
    on_intel do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v0.2.0/onesie_0.2.0_linux_amd64.tar.gz"
      sha256 "09f20a22ced4fdedbcd90eb775ece444bae1fa9f7196537229ffe4e29aff0ff1"
    end
  end

  def install
    bin.install "onesie"
    bash_completion.install "completions/onesie.bash" => "onesie"
    zsh_completion.install "completions/onesie.zsh" => "_onesie"
    fish_completion.install "completions/onesie.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/onesie version")
  end
end
