# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workshed < Formula
  desc "A tool for managing local development environments"
  homepage "https://github.com/frodi-karlsson/workshed"
  version "0.2.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/frodi-karlsson/workshed/releases/download/v0.2.9/workshed_darwin_amd64.tar.gz"
      sha256 "8aca0a5e2d2915cd66bce6d12e9fe0753ec4128f8809823815eb96278b4aec30"

      def install
        bin.install "workshed"
      end
    end
    on_arm do
      url "https://github.com/frodi-karlsson/workshed/releases/download/v0.2.9/workshed_darwin_arm64.tar.gz"
      sha256 "8bdc074626d4f36aa5a37fc43d79e9fe199dee5701b6bfd1980eaf9e9fa7e22a"

      def install
        bin.install "workshed"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/frodi-karlsson/workshed/releases/download/v0.2.9/workshed_linux_amd64.tar.gz"
        sha256 "c9344398bcb23b146a1d7ec8ea32b0b9ec29862b1a037d90d193822ac8df9b1c"

        def install
          bin.install "workshed"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/frodi-karlsson/workshed/releases/download/v0.2.9/workshed_linux_arm64.tar.gz"
        sha256 "d04e1fae185c6c0c56553244b34c4e9d61252df9884c8126f0251db45607511d"

        def install
          bin.install "workshed"
        end
      end
    end
  end
end
