# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Workshed < Formula
  desc "A tool for managing local development environments"
  homepage "https://github.com/frodi-karlsson/workshed"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/frodi-karlsson/workshed/releases/download/v0.4.0/workshed_darwin_amd64.tar.gz"
      sha256 "fccd8a7fef6485e9ca7e0d544cf1ca0281ef7d2d1b2e239f8b7c4146e5a31506"

      def install
        bin.install "workshed"
      end
    end
    on_arm do
      url "https://github.com/frodi-karlsson/workshed/releases/download/v0.4.0/workshed_darwin_arm64.tar.gz"
      sha256 "a650a4627b39b3aea760a7f280bc663730d4cf253b163b465eb1a207dd683c02"

      def install
        bin.install "workshed"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/frodi-karlsson/workshed/releases/download/v0.4.0/workshed_linux_amd64.tar.gz"
        sha256 "2e6a93aeab736f3cefb6216ac7e34f86f9bbe1ff1a61657543e8c5b56b964da1"

        def install
          bin.install "workshed"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/frodi-karlsson/workshed/releases/download/v0.4.0/workshed_linux_arm64.tar.gz"
        sha256 "bfb1b8c6f2bd5703bcf436a9a374d1981b6451909da02388b829e29f5670377e"

        def install
          bin.install "workshed"
        end
      end
    end
  end
end
