# This file was generated by GoReleaser. DO NOT EDIT.
cask "app-audit" do
  version "0.1.0"

  on_macos do
    sha256 "9362ee51b6613f31333ddede36f0a57dc3c7e82480ac9adc32dc2f7cfeccb174"
    url "https://github.com/frodi-karlsson/agentic-app-audit/releases/download/v#{version}/app-audit_darwin_all.tar.gz"
  end

  name "app-audit"
  desc "Audit installed macOS software for staleness and open CVEs"
  homepage "https://github.com/frodi-karlsson/agentic-app-audit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "app-audit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/app-audit"]
    end
  end

  # No zap stanza required

end
