# This file was generated by GoReleaser. DO NOT EDIT.
cask "app-audit" do
  version "0.2.0"

  on_macos do
    sha256 "287c90b951b15b0e024114d6962d91b1e00aff8c44a268fd515372f07f2cc735"
    url "https://github.com/frodi-karlsson/agentic-app-audit/releases/download/v#{version}/app-audit_darwin_all.tar.gz"
  end

  name "app-audit"
  desc "Audit installed macOS software for staleness and open CVEs"
  homepage "https://github.com/frodi-karlsson/agentic-app-audit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "app-audit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/app-audit"]
    end
  end

  # No zap stanza required

end
