# This file was generated by GoReleaser. DO NOT EDIT.
cask "pni" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "70848597cf447c3ee3857f835f8ac1c3b43bd5ccbf634ef01fdfe9865885728d"
      url "https://github.com/frodi-karlsson/pni/releases/download/v#{version}/pni_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "952aa0ea638a9f2faa5198434ab30f7fe229ef2cc667acd1886a7ceb77cc26dc"
      url "https://github.com/frodi-karlsson/pni/releases/download/v#{version}/pni_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f2c67290b2ce3d9b1cc214428b2471902f75607294fe7dd3eea135c9d464c92f"
      url "https://github.com/frodi-karlsson/pni/releases/download/v#{version}/pni_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2679e800e2cc4a0049c8397bdb6638518ac5df928cdea216f3c6f9641049b49c"
      url "https://github.com/frodi-karlsson/pni/releases/download/v#{version}/pni_linux_amd64.tar.gz"
    end
  end

  name "pni"
  desc "pnpm install with automatic npm token recovery from 1Password"
  homepage "https://github.com/frodi-karlsson/pni"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pni"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pni"]
    end
  end

  # No zap stanza required
end
