# This file was generated by GoReleaser. DO NOT EDIT.
cask "pnop" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "90250ca5babd10750e60e82fb8dd63f585f708258f505a3366dfaf1bc889dce6"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5c0677d17c394b97584fc2469eb592edd830464906d7dc786140ff4886b5c039"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f2dbb3637d3c22f1067f03df5cf53b31927238df448e0941f1c5f77e6ce8df23"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "70029a5a1a65d7389846615c8c0a10894757a635c506a7ddcb00a97eef7bd45e"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_linux_amd64.tar.gz"
    end
  end

  name "pnop"
  desc "pnpm with automatic npm token recovery from 1Password"
  homepage "https://github.com/frodi-karlsson/pnop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pnop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pnop"]
    end
  end

  # No zap stanza required
end
