# This file was generated by GoReleaser. DO NOT EDIT.
cask "pnop" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "29d6cf6122964fae892026a791960bed8b95a8fce555f9f672104b0c6e545b38"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6c7832c30f49c72f7e272a44368f5d86651bd67b010ad0585b3650b2e927287f"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "55f40499dd48633247534af9e7418aef4632c10d3f210861c95dc9e5c40f77b3"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0af77d22aebc34a524a204614a8ebf793d3c8ad20497273a4844c51e20dbcaaf"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_linux_amd64.tar.gz"
    end
  end

  name "pnop"
  desc "pnpm with automatic npm token recovery from 1Password"
  homepage "https://github.com/frodi-karlsson/pnop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pnop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pnop"]
    end
  end

  # No zap stanza required
end
