# This file was generated by GoReleaser. DO NOT EDIT.
cask "pnop" do
  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "0223049e407ddc462fd8fe33a870a6f3f816c338e95eaffddecdddda9b6bd158"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "98e049edc407b88471316926904a40855b8088a836464d4ce68ee191094f5acd"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cba90d0d75d577a35bc63e84ad4c99b0dd4f2273d7d03ed4649c35ac9888d478"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7560469a0c32f916dd870128e50ed27a107a2a0a1e682d24faba906376518e64"
      url "https://github.com/frodi-karlsson/pnop/releases/download/v#{version}/pnop_linux_amd64.tar.gz"
    end
  end

  name "pnop"
  desc "pnpm with automatic npm token recovery from 1Password"
  homepage "https://github.com/frodi-karlsson/pnop"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "1password-cli",
    ]

  binary "pnop"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pnop"]
    end
  end

  # No zap stanza required
end
